---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "scsplit_run"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::scsplit=1.0.8.2"
